import mongoose from "mongoose";

export interface WhatsAppMessageData {
  messageId: string; // Twilio message SID
  from: string; // WhatsApp phone number (sender)
  to: string; // Twilio WhatsApp number (receiver)
  body: string; // Message content
  orderId?: mongoose.Types.ObjectId; // Reference to Order (if order generated)
  analyzed: boolean; // Whether AI has analyzed this message
  analysisResult?: {
    extractedData?: any; // AI extracted order data
    confidence?: number; // AI confidence score
    error?: string; // Error message if analysis failed
  };
  createdAt?: Date; // Optional, auto-generated by timestamps
}

const whatsappMessageSchema = new mongoose.Schema(
  {
    messageId: {
      type: String,
      required: true,
      unique: true,
    },
    from: {
      type: String,
      required: true,
    },
    to: {
      type: String,
      required: true,
    },
    body: {
      type: String,
      required: true,
    },
    orderId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Order",
    },
    analyzed: {
      type: Boolean,
      default: false,
    },
    analysisResult: {
      type: {
        extractedData: mongoose.Schema.Types.Mixed,
        confidence: Number,
        error: String,
      },
    },
  },
  {
    timestamps: true,
  }
);

const WhatsAppMessage =
  mongoose.models.WhatsAppMessage ||
  mongoose.model("WhatsAppMessage", whatsappMessageSchema);

export default WhatsAppMessage;

